### ISSUE TITLE
Add a monitoring docker

### ISSUE THREAD

**Issue by sgerrand** [FundingCircle/kafka-compose#7]
> Add a monitoring docker (Already have the perfect candidate)

This note was added to the README [back in June](../commit/144efaa49dbd7dfeefbfb90f71d58a53a7b93bb7). Will this new container be added to the `docker-compose.yml` file?

**Comment by DayoOliyide** [comment]
That is probably not needed at the moment. As you've rightly pointed out, I made that note in June .... my understanding of what was needed for this docker-compose project has changed since then.

**Comment by sgerrand** [comment]
Thanks for the feedback, I've removed the note in #9. :ok_woman:
